name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies (Backend)
      run: cd backend && npm install
    - name: Lint (Backend)
      run: cd backend && npm run lint
    - name: Test (Backend)
      run: cd backend && npm test
    - name: Build (Backend)
      run: cd backend && npm run build
    - name: Install dependencies (Frontend)
      run: cd frontend && npm install
    - name: Lint (Frontend)
      run: cd frontend && npm run lint
    - name: Test (Frontend)
      run: cd frontend && npm test
    - name: Build (Frontend)
      run: cd frontend && npm run build
